// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.anubhav.proto;

public interface StudentsClassOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StudentsClass)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Student students = 1;</code>
   */
  java.util.List<com.anubhav.proto.Student> 
      getStudentsList();
  /**
   * <code>repeated .Student students = 1;</code>
   */
  com.anubhav.proto.Student getStudents(int index);
  /**
   * <code>repeated .Student students = 1;</code>
   */
  int getStudentsCount();
  /**
   * <code>repeated .Student students = 1;</code>
   */
  java.util.List<? extends com.anubhav.proto.StudentOrBuilder> 
      getStudentsOrBuilderList();
  /**
   * <code>repeated .Student students = 1;</code>
   */
  com.anubhav.proto.StudentOrBuilder getStudentsOrBuilder(
      int index);
}
