// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.anubhav.proto;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();
}
